// Package main runs the REST API server.
//
//	@title           Go Service Template API
//	@version         1.0
//	@description     Production-ready feature-driven REST API template.
//	@termsOfService  http://swagger.io/terms/
//
//	@contact.name   API Support
//	@contact.url    https://github.com/go-service-template
//
//	@license.name  Apache 2.0
//	@license.url   http://www.apache.org/licenses/LICENSE-2.0.html
//
//	@host      localhost:8080
//	@BasePath  /
//
//	@externalDocs.description  OpenAPI
//	@externalDocs.url          https://swagger.io/resources/open-api/
package main

import (
	"os"

	"github.com/gin-gonic/gin"

	"go-service-template/internal/config"
	"go-service-template/internal/health"

	_ "go-service-template/cmd/server/docs" // generated by swag init
)

func main() {
	if err := run(); err != nil {
		_, _ = os.Stderr.WriteString(err.Error() + "\n")
		os.Exit(1)
	}
}

func run() error {
	_ = config.Load
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	router := gin.New()
	router.Use(gin.Recovery())

	healthHandler := health.NewHandler()
	health.Register(router, healthHandler, cfg.Health)

	return router.Run(":" + cfg.Server.Port)
}
